# Generated by Django 4.2.3 on 2023-08-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
    ]
