# Generated by Django 4.2.3 on 2023-08-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0002_rename_contactmessage_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
