# Generated by Django 4.2.3 on 2023-08-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0005_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='carousel/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
