# Generated by Django 4.2.3 on 2023-08-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0007_alter_carouselitem_image_alter_carouselitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
