# Generated by Django 4.2.3 on 2023-08-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0008_alter_carouselitem_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours', models.TextField()),
                ('appointment_date_placeholder', models.CharField(max_length=100)),
                ('services', models.TextField()),
                ('contact_information', models.CharField(max_length=100)),
            ],
        ),
    ]
