# Generated by Django 4.2.3 on 2023-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0010_openinghours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghours',
            old_name='day',
            new_name='day2',
        ),
        migrations.RenameField(
            model_name='openinghours',
            old_name='hours',
            new_name='hours1',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='day1',
            field=models.CharField(default='Mon - Fri', max_length=20),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='day3',
            field=models.CharField(default=3777, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openinghours',
            name='hours2',
            field=models.CharField(default=83684, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openinghours',
            name='hours3',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
