# Generated by Django 4.2.3 on 2023-08-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0011_rename_day_openinghours_day2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length='150')),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
