# Generated by Django 4.2.3 on 2023-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0013_aboutcontent_delete_bannercontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontent',
            name='points',
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='title',
            field=models.CharField(default='Say Something nice', max_length=200),
        ),
    ]
