# Generated by Django 4.2.3 on 2023-08-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0015_alter_aboutcontent_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
