# Generated by Django 4.2.3 on 2023-08-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0016_appointment_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment_Text',
            new_name='HomeContent',
        ),
    ]
