# Generated by Django 4.2.3 on 2023-08-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0020_remove_service_description_alter_service_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('testimonial_text', models.TextField()),
                ('image_url', models.ImageField(upload_to='Testimonial/%y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.ImageField(upload_to='Service/%y/%m/%d/'),
        ),
    ]
