# Generated by Django 4.2.3 on 2023-08-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0024_rename_student_reg_patient_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patient_reg',
            new_name='PatientRegistration',
        ),
    ]
