# Generated by Django 4.2.3 on 2023-08-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0025_rename_patient_reg_patientregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregistration',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='maritalstat',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='medical_condition',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='taking_medications',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='weight',
        ),
    ]
