# Generated by Django 4.2.3 on 2023-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0027_patientregistration_admission_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientregistration',
            old_name='username',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='admission_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='allergies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='department',
            field=models.CharField(choices=[('Dbfs', 'Department of Biology and Forensic Science'), ('Dcos', 'Department of Computing Science'), ('Dplp', 'Department of Public Law and Private Law'), ('Dabae', 'Department of Accounting/Business Administration/Economics'), ('Delhi', 'Department of English & Literary Studies/History & International Studies'), ('Dit', 'Department of International Relations/Hospitality & Tourism Studies')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='faculty',
            field=models.CharField(choices=[('fos', 'Faculty of Science'), ('fams', 'Faculty of Arts and Management Science'), ('fol', 'Faculty of Law')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='gender',
            field=models.CharField(choices=[('girl', 'Female'), ('boy', 'Male')], max_length=4, null=True),
        ),
    ]
