# Generated by Django 4.2.3 on 2023-08-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0028_rename_username_patientregistration_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregistration',
            name='password',
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='password1',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='password2',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
