# Generated by Django 4.2.3 on 2023-08-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0030_staffregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregistration',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='room_number',
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='Services_Rendered',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='department',
            field=models.CharField(choices=[('doc', 'Doctor'), ('nurse', 'Nurse'), ('pharm', 'pharmacist'), ('con', 'consultant'), ('lab', 'Laboratory')], max_length=10, null=True),
        ),
    ]
