# Generated by Django 4.2.3 on 2023-08-27 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adun', '0036_patient_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='marital_status',
            new_name='maritalstat',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admission_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='room_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
