# Generated by Django 4.2.3 on 2023-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0039_patientregistration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('girl', 'Female'), ('boy', 'Male')], max_length=4)),
                ('maritalstat', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], max_length=10)),
                ('faculty', models.CharField(choices=[('fos', 'Faculty of Science'), ('fams', 'Faculty of Arts and Management Science'), ('fol', 'Faculty of Law')], max_length=20)),
                ('department', models.CharField(choices=[('Dbfs', 'Department of Biology and Forensic Science'), ('Dcos', 'Department of Computing Science'), ('Dplp', 'Department of Public Law and Private Law'), ('Dabae', 'Department of Accounting/Business Administration/Economics'), ('Delhi', 'Department of English & Literary Studies/History & International Studies'), ('Dit', 'Department of International Relations/Hospitality & Tourism Studies')], max_length=20)),
                ('admission_number', models.CharField(max_length=20)),
                ('room_number', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allergies', models.TextField()),
                ('medical_condition', models.TextField()),
                ('taking_medications', models.BooleanField()),
                ('medications', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientRegistration',
        ),
    ]
