# Generated by Django 4.2.3 on 2023-08-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0042_patientregistration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregistration',
            name='user',
        ),
    ]
