# Generated by Django 4.2.3 on 2023-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0046_alter_patientregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
