# Generated by Django 4.2.3 on 2023-09-01 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0047_patientregistration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='room_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
