# Generated by Django 4.2.3 on 2023-09-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0052_alter_patientregistration_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='gender',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Female', 'Female'), ('Male', 'Male')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='maritalstat',
            field=models.CharField(choices=[('Select', 'Select'), ('Gender', 'Gender'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='gender',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Female', 'Female'), ('Male', 'Male')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='qualification',
            field=models.CharField(choices=[('Select', 'Select'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('pharmacist', 'pharmacist'), ('consultant', 'consultant'), ('Laboratory', 'Laboratory')], max_length=30, null=True),
        ),
    ]
