# Generated by Django 4.2.3 on 2023-09-02 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adun', '0055_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='maritalstat',
            field=models.CharField(choices=[('Select', 'Select'), ('Gender', 'Gender'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=100, null=True),
        ),
    ]
