# Generated by Django 4.2.3 on 2023-09-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0057_alter_staffregistration_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='id_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
