# Generated by Django 4.2.3 on 2023-09-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0058_patientregistration_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregistration',
            name='id_number',
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='admission_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
